export const data = [
  {
    id: 2,
    link: 'https://assets.mixkit.co/videos/preview/mixkit-going-down-a-curved-highway-down-a-mountain-41576-large.mp4',
    title: 'tree',
    product_title: 'new year tree',
    product_image_link: 'https://appleinsider.ru/wp-content/uploads/2021/12/macbook_secon_display_howto-740x534.jpg',
    product_link: 'https://th.bing.com/th/id/R.b6f03b06334b88006bd44b21a1f0d85a?rik=Vgnny98tlpUQjA&pid=ImgRaw&r=0',
    hashtag: '#holiday',
    isTranding: true,
    likes: 21,
    created_at: '2022-01-21T11:00:40.183Z',
    userId: 6,
    user: {
      id: 6,
      first_name: 'Mick',
      second_name: 'Swanson',
      email: 'shevchukren@gmail.com',
      avatar: 'empty',
      header: 'empty',
      description: 'Welcome on my profile, follow and you will see my new videos soon!',
      plan: null,
      plan_end_date: '2022-01-21T10:04:47.610Z',
      is_blocked: true,
      stripe_customer_id: 'cus_L0Ma3lznIvFdl7',
    },
  },
  {
    id: 1,
    link: 'https://assets.mixkit.co/videos/preview/mixkit-people-pouring-a-warm-drink-around-a-campfire-513-large.mp4',
    title: 'news',
    product_title: 'creating news',
    product_image_link:
      'https://cdn.vox-cdn.com/thumbor/1RotWNHPH9m_eId_y7FIB1eT2f4=/0x0:1750x1165/1400x933/filters:focal(735x443:1015x723):no_upscale()/cdn.vox-cdn.com/uploads/chorus_image/image/67035058/HR_EOS_R5_3.0.jpg',
    product_link: 'https://github.com/typeorm/typeorm/issues/4358sadasdasd',
    hashtag: '#news',
    isTranding: false,
    likes: 2,
    created_at: '2022-01-21T09:30:56.706Z',
    userId: 1,
    user: {
      id: 1,
      first_name: 'Joey Melanson',
      second_name: 'Шевчук',
      email: 'ignatognevic@gmail.com',
      avatar: 'empty',
      header: 'empty',
      description: 'Hi everyone, hope you have a great day',
      plan: 'non',
      plan_end_date: '2022-01-18T09:25:17.262Z',
      is_blocked: false,
      stripe_customer_id: '',
    },
  },
  {
    id: 1,
    link: 'https://assets.mixkit.co/videos/preview/mixkit-highway-in-the-middle-of-a-mountain-range-4633-large.mp4',
    title: 'news',
    product_title: 'creating news',
    product_image_link:
      'https://cdn.vox-cdn.com/thumbor/1RotWNHPH9m_eId_y7FIB1eT2f4=/0x0:1750x1165/1400x933/filters:focal(735x443:1015x723):no_upscale()/cdn.vox-cdn.com/uploads/chorus_image/image/67035058/HR_EOS_R5_3.0.jpg',
    product_link: 'https://github.com/typeorm/typeorm/issues/4358sadasdasd',
    hashtag: '#news',
    isTranding: false,
    likes: 2,
    created_at: '2022-01-21T09:30:56.706Z',
    userId: 1,
    user: {
      id: 1,
      first_name: 'Joey Melanson',
      second_name: 'Шевчук',
      email: 'ignatognevic@gmail.com',
      avatar: 'empty',
      header: 'empty',
      description: 'Hi everyone, hope you have a great day',
      plan: 'non',
      plan_end_date: '2022-01-18T09:25:17.262Z',
      is_blocked: false,
      stripe_customer_id: '',
    },
  },
];
