export const following = [
  {
    id: 19,
    first_name: 'Renat',
    second_name: 'Shevchuk',
    username: 'RenatShev',
    email: 'shevchukren@gmail.com',
    avatar: 'https://lh3.googleusercontent.com/a/AATXAJyctuSoKFvUd12oZmqDTQbO4dvjux5d5xyd54tB=s96-c',
    header: 'empty',
    description: 'empty',
    website_link: '',
    plan: 'base',
    plan_end_date: '2022-01-24T10:10:20.986Z',
    is_blocked: true,
    stripe_customer_id: 'cus_L1UMsOUXj3HKXF',
  },
  {
    id: 18,
    first_name: 'Виктория',
    second_name: 'Денеко',
    username: 'Vika123',
    email: 'heatherdein354@gmail.com',
    avatar: 'https://lh3.googleusercontent.com/a/AATXAJwaMVrXafnAdHL3Afc5-a5EgEkhmOJMEmd36dqR=s96-c',
    header: '',
    description: '',
    website_link: '',
    plan: 'non',
    plan_end_date: '2022-01-24T10:06:59.640Z',
    is_blocked: true,
    stripe_customer_id: 'cus_L1UIbQnO9NzVHu',
  },
  {
    id: 3,
    first_name: 'Lyuda',
    second_name: 'Dziubynska',
    username: 'LuidaDz',
    email: 'lyuda@zenbit.tech',
    avatar: 'null',
    header: 'empty',
    description: 'empty',
    website_link: '',
    plan: 'non',
    plan_end_date: '2022-01-18T11:10:41.405Z',
    is_blocked: false,
    stripe_customer_id: '',
  },
  {
    id: 1,
    first_name: 'Рен',
    second_name: 'Шевчук',
    username: 'Ren',
    email: 'ignatognevic@gmail.com',
    avatar: 'null',
    header: 'Hello! I am Renat and I am developer',
    description: 'We are Zenbit Tech company',
    website_link: '',
    plan: 'non',
    plan_end_date: '2022-01-18T09:25:17.262Z',
    is_blocked: false,
    stripe_customer_id: '',
  },
];
